### ISSUE TITLE
[Forge 1.19.2] Misaligned GUI in the dual-crafting workstation

### ISSUE THREAD

**Issue by Nereithr** [moonfather1/workshop_for_handsome_adventurer#2]
First of all, great mod. The only issue I'm running into is a misaligned GUI in the Workstation. I tested this with a variety of setups:

- Other mods vs JEI/EMI-only vs no mods (except this one of course)
- Different GUI scales
- JEI/EMI overlay open or closed
- Chest upgrade vs no chest upgrade
- Different versions of the mod, specifically 1.11 and 1.10

The issue persists in all of the above setups. Forge version is latest for 1.19.2

Image attached

![2023-12-15_03 21 15](https://github.com/moonfather1/workshop_for_handsome_adventurer/assets/72263884/1083c7c0-7771-4fab-bc89-a7e294ad6908)

**Comment by moonfather1** [comment]
well that's not good.

looks like it's just a bad background image... when i added support for crafting tweaks (adds buttons to the left of crafting grids) i moved crafting grids to the right. could be i just left the old png files in 1.19 version. i'll look into it today. thanks.

if i'm right and if you're in a hurry, you can borrow png images from 1.20.

**Comment by Nereithr** [comment]
Thank you for the prompt response. You are right, just checked it and it is indeed just the old png in the 1.19.2 version, fixable with a resource pack of the new files.

I additionally ran into a rare rendering issue (mostly noticed it just after initial world loads) where the items on tool racks (only noticed it on those specifically) don't visually update (i.e. they still functionally move between the player inventory and various slots, just not visually) until a block update is triggered nearby (or several seconds pass and all nearby chunks fully load), I will file a separate issue once I can reproduce it consistently. 

Small update on this: can't reproduce it with the "vanilla" forge-only setup, so it's probably one of the rendering mods I have interacting with it in this way. The issue also only lasts for a couple of seconds and only on the game's very first initial load, so I'm not sure if this is worth reporting at all.

**Comment by moonfather1** [comment]
i uploaded version 1.11b for 1.19.2. it was just a 3-customization-slots png that was the old version. other 4 variants (0.1.2.4 slots) were fine.     thanks again. closing.

as for rendering issue, first of all if you're using optifine, don't report issues to any modder, we don't want anything to do with it. if it's sodium (likely embeddium in your case?) i would be willing to work on an issue although it should likely be they (EmbeddedT) investigating and fixing.

**Comment by Nereithr** [comment]
Using Embeddium, but also ImmediatelyFast, which is known to be incompatible with some mods. I will file an issue if this proves to be an actually annoying issue and not just an adhd thing of needing to interact with a tool rack within 3 seconds of loading the world.

> i uploaded version 1.11b for 1.19.2. it was just a 3-customization-slots png that was the old version. other 4 variants (0.1.2.4 slots) were fine. thanks again. closing.
> 
> as for rendering issue, first of all if you're using optifine, don't report issues to any modder, we don't want anything to do with it. if it's sodium (likely embeddium in your case?) i would be willing to work on an issue although it should likely be they (EmbeddedT) investigating and fixing.

**Comment by Nereithr** [comment]
@moonfather1 Sorry for pestering you, but I narrowed down the rendering issue to a cross-mod interaction between Embeddium and Chunk Sending and it occurs with other tool rack mods, so this actually has nothing to do with your code at all :) I will create an issue on their end.
