### ISSUE TITLE
[1.20.1-1.14.1] After updating to this version, mod causes a startup crash

### ISSUE THREAD

**Issue by Gronglegrowth** [moonfather1/workshop_for_handsome_adventurer#3]
I was previously using version 1.13 with no issue, but upon updating to 1.14.1, the game crashes - if not this mod as the cause, it's definitely involved, as disabling it allows the game to load fine. I suspect it might be related to the modded wood support, but not entirely sure?

Here is the logfile: https://paste.gg/p/anonymous/bce0413d96c94f0890d8f9a06d9e3685

**Comment by moonfather1** [comment]
on it.

**Comment by moonfather1** [comment]
i believe i fixed it. by bad.
vinery added their cherry wood and while i had (limited) support for modded duplicates, i didn't expect someone would duplicate one of woods from base game.

anyway please try 1.14.3 and let me know if it's ok...

**Comment by Gronglegrowth** [comment]
Yes, version 1.14.3 (and .4) works.
