### ISSUE TITLE
Item deletion on sorting

### ISSUE THREAD

**Issue by jeytee84** [moonfather1/workshop_for_handsome_adventurer#5]
[Video](https://imgur.com/a/Z1IC6cJ)

Sorting done by [Inventory Tweaks - ReFoxed](https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-refoxed)

**Comment by moonfather1** [comment]
issue acknowledged.

i need to see with this other mod's devs how we'd have them leave the customization slots alone.

**Comment by remghoost** [comment]
+1 on this.
Using [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next).

Will also mention that some items are duplicated as well.

---
edit: This can be avoided with this mod by opening the crafting table, pressing "r + g", and enabling "Player Only" on the right side.

**Comment by moonfather1** [comment]
@remghoost 
hold on.
game version? mod version?

i fixed inventory tweaks refoxed in latest version. do you have latest version of workshop?
if not, it's fine, just edit **invtweaks-client.toml** and add an override for my tables (moonfather.workshop_for_handsome_adventurer.block_entities.*)

**Comment by blackd** [comment]
I was able to reproduce the item duplication with IPN on 1.21

**Comment by remghoost** [comment]
Minecraft - 1.19.2
Handsome Adventurer - 1.15.2
Inventory Profiles Next - 1.10.10
